apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: api-ia-web
type: Opaque
data:
  db-username: bmVvbmRiX293bmVy
  db-password: bnBnXzFuVFN4OHNKdlB1cg==
  openrouter-key: c2stb3ItdjEtNTY3MWRjMzE2OTMxZjI3NWMwNzU1NGE0MTI4NDg3Y2U1OWU1ZWIyOTZlNmJlZmJkNGE1Y2M4OGIyZDY1YmZlNw==
  mistral-key: TnE5Y05tcTNsQWV3aWc0WmE3QVRPQmtvM2ROQVhIVWM=
